---
title: "clean"
author: "wzm"
date: "12/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cluster)
library(plyr)
library(tidyverse)
```

```{r functions}
one_hot <- function(df, cols="auto",dropCols=T){
  if(cols[1] == "auto") cols <- colnames(df)[which(sapply(df, function(x) is.factor(x) & !is.ordered(x)))]
  for(col in cols){
    lv <- levels(df[[col]])
    for(i in lv){
      st <- str_c(col,i,sep = "_")
      df[[st]] <- ifelse( df[[col]]==i, 1,0) 
    }
  }
  if(dropCols == T) df[!names(df) %in% cols]
  else df
}
path <- function(st){ str_c("data",st,sep='/')}
```

```{r setting}
n_cluster <- 10
```

```{r loading}
# load upcbr #
upcbr <- read_csv(path("upcbr.csv"))
colnames(upcbr) <- tolower(colnames(upcbr))
upcbr <- plyr::rename(upcbr[2:5], c("descrip" = "name"))
upcbr <- upcbr %>% left_join( read_csv(path('brand.csv')), by = c('upc' = 'UPC') ) %>% 
                  left_join( read_csv(path('vol.csv')), by = 'upc')
upcbr[is.na(upcbr$brand),]$brand <- 'other'
upcbr[is.na(upcbr$type),]$type <- 'other'

# load mvbr #
mvbr <- drop_na(read_csv(path("mvbr.csv"),col_types = cols(SALE = col_character())),c("UPC"))
colnames(mvbr) <- tolower(colnames(mvbr))
mvbr <- plyr::rename(mvbr[-c(10,11)], c("qty" = "bundle","store" = "store_id","move" = "sold")) 

# load demo #
demo <- drop_na(read_csv(path("demo.csv")),c("name")) %>% 
        select( mmid:shpindx ) %>%
        plyr::rename(c("store" = "store_id", "name" = "store"))

demo_cls <- demo %>% select(-c(mmid,store,city,zip,lat,long,store_id,scluster,zone))
demo$cluster <- clara(demo_cls,n_cluster,correct.d=TRUE)[['clustering']]
rm(demo_cls)

# load cc #
# cc <- drop_na(read('ccount.csv'),c("date","grocery")) %>% 
#       rename(c("store" = "store_id"))
```

```{r mvbr-processing}
# merging #
mvbr <-  left_join(mvbr, upcbr, by = "upc" ) %>%
        left_join( demo, by = "store_id") %>%
        mutate( sale = ifelse( is.na(sale)==FALSE, sale, "N")) %>% 
        left_join( read_csv(path("cc_brn.csv")), by = c("store_id", "week"))

# different sale dummy #
mvbr$sale <- factor(mvbr$sale)
mvbr <- one_hot(mvbr) %>% mutate( sale = ifelse( sale_N != 1, 1,0))
mvbr$sale_N <- NULL

# different store_id dummy # unused
mvbr$store_id<-factor(mvbr$store_id) # 89
# mvbr <- one_hot(mvbr)

festival_week <- c(7,11,15,16,23,28,59,63,67,37,68,42,75,51,81,89,95,119,120,128,103,112,
                  116,133,141,147,156,164,168,180,185,194,199,172,173,208,216,220,224,225,
                  232,246,251,260,238,268,272,276,277,284,303,312,289,298,320,324,328,329,
                  336,341,364,372,377,50,356,380,381,389,393)
mvbr <-  mvbr %>% mutate( fstv = ifelse(week %in% festival_week, 1, 0)) %>%
                  mutate( rev = sold * price)
rm(festival_week)

mvbr$brand <- factor(mvbr$brand) # 48
mvbr$type <- factor(mvbr$type) # 28
```

```{r variable selection}
colnames(mvbr)

###  sum(is.na(mvbr$gini)) # All none.

###   some store do not have demographic data  ###
###  sum(is.na(mvbr$educ)) # 29082 
###  unique(mvbr[is.na(mvbr$educ),]$store_id) # 136 140 133 135 141 142 143 144 146 139
###  sum(mvbr$store_id %in% mvbr[is.na(mvbr$educ),]$store_id) # 29082

mvbeer <- select(mvbr,c( store_id, week, upc,brand, type, rev, sale, vol, fstv,cluster,price,sale_B:sale_S))

mvbeer <- mvbeer %>% group_by(store_id, week) %>%
  dplyr::mutate(highrev = ifelse(rev >= sum(rev)/n_distinct(upc) && rev>0, 1, 0) )

## quantilization ## unused
# mvbeer <- mvbeer %>% 
#   mutate( ethn = as.numeric( ( cut(mvbeer$ethnic, breaks =seq(0,1, by =0.05))))) %>%
#   mutate( age9 = as.numeric( ( cut(mvbeer$age9, breaks =seq(0,1, by =0.05))))) %>%
#   mutate( age60 = as.numeric( ( cut(mvbeer$age60, breaks =seq(0,1, by =0.05))))) %>%
#   mutate( educ = as.numeric( ( cut(mvbeer$educ, breaks =seq(0,1, by =0.05)))))

```

```{r clean and store}
rm(demo);rm(mvbr);rm(upcbr);rm(one_hot);rm(path);rm(n_cluster)
# write_csv(mvbeer,"data/mvbeer.csv")
```
